Repository YJ941108/ft_transcendence, pull requests merged in 2022-08, with the labels that each got.

#58 Feature/back/chat
  srcs/back/src/app.module.ts
  srcs/back/src/enums/games.enum.ts
  srcs/back/src/modules/auth/jwt.strategy.ts
  srcs/back/src/modules/channel/channel.module.ts
  srcs/back/src/modules/channel/channel.service.ts
  srcs/back/src/modules/channel/dto/create-channel.dto.ts
  srcs/back/src/modules/channel/dto/update-channel.dto.ts
  srcs/back/src/modules/channel/entities/channel.entity.ts
  srcs/back/src/modules/chat/chat.filter.ts
  srcs/back/src/modules/chat/chat.gateway.ts
  srcs/back/src/modules/chat/chat.module.ts
  srcs/back/src/modules/chat/chat.service.ts
  srcs/back/src/modules/chat/class/chat-user.class.ts
  srcs/back/src/modules/chat/class/chat-users.class.ts
  srcs/back/src/modules/direct-message/direct-message.module.ts
  srcs/back/src/modules/direct-message/direct-message.service.ts
  srcs/back/src/modules/direct-message/dto/create-direct-message.dto.ts
  srcs/back/src/modules/direct-message/dto/update-direct-message.dto.ts
  srcs/back/src/modules/direct-message/entities/direct-message.entity.ts
  srcs/back/src/modules/games/dto/create-game.dto.ts
  srcs/back/src/modules/games/games.controller.ts
  srcs/back/src/modules/games/games.entity.ts
  srcs/back/src/modules/games/games.gateway.ts
  srcs/back/src/modules/games/games.module.ts
  srcs/back/src/modules/message/dto/create-message.dto.ts
  srcs/back/src/modules/message/dto/update-message.dto.ts
  srcs/back/src/modules/message/entities/message.entity.ts
  srcs/back/src/modules/message/message.module.ts
  srcs/back/src/modules/message/message.service.ts
  srcs/back/src/modules/punishment/entities/punishment.entity.ts
  srcs/back/src/modules/punishment/punishment.module.ts
  srcs/back/src/modules/punishment/punishment.service.ts
  srcs/back/src/modules/users/entities/users.entity.ts
  srcs/back/src/modules/users/users.controller.ts
  srcs/back/src/modules/users/users.gateway.ts
  srcs/back/src/modules/users/users.repository.ts
  srcs/back/src/modules/users/users.service.ts
  srcs/back/src/utils/patternValidator.ts
Labels: enhancement

#65 FT-93 [feat] modal라이브러리
  srcs/front/package-lock.json
  srcs/front/package.json
  srcs/front/src/App.tsx
  srcs/front/src/components/profile/ProfileCard.tsx
  srcs/front/src/components/profile/ProfileModal.tsx
  srcs/front/src/components/profile/UserInterface.ts
  srcs/front/src/components/styles/Modal.css
  srcs/front/src/modules/api.ts
  srcs/front/src/routes/Router.tsx
  srcs/front/src/routes/pages/ProfileEditPage.tsx
Labels: enhancement

#68 Feature/back/chat
  srcs/back/src/modules/channel/channel.service.ts
  srcs/back/src/modules/channel/dto/create-channel.dto.ts
  srcs/back/src/modules/chat/chat.controller.ts
  srcs/back/src/modules/chat/chat.gateway.ts
  srcs/back/src/modules/chat/chat.module.ts
  srcs/back/src/modules/chat/chat.service.ts
  srcs/back/src/modules/direct-message/direct-message.service.ts
  srcs/back/src/modules/games/games.gateway.ts
  srcs/back/src/modules/message/message.service.ts
  srcs/back/src/modules/users/entities/users.entity.ts
  srcs/back/src/modules/users/users.repository.ts
  srcs/back/src/modules/users/users.service.ts
Labels: enhancement

#78 Input css 수정
  srcs/front/src/components/profile/ProfileCard.tsx
  srcs/front/src/components/profile/ProfileContent.tsx
  srcs/front/src/components/profile/ProfileModal.tsx
  srcs/front/src/components/profile/Toggle.tsx
  srcs/front/src/components/styles/Modal.css
  srcs/front/src/routes/pages/ProfilePage.tsx
Labels: enhancement, style

#86 Feature/front/dm
  srcs/front/public/RetroGaming.ttf
  srcs/front/src/GlobalStyle.tsx
  srcs/front/src/modules/styled.d.ts
  srcs/front/src/modules/theme.ts
Labels: style

#88 Feature/front/profile
  srcs/front/public/img/firstFriend.png
  srcs/front/public/img/firstLogin.png
  srcs/front/public/img/firstWin.png
  srcs/front/public/img/loss.png
  srcs/front/public/img/ratio.png
  srcs/front/public/img/win.png
  srcs/front/src/components/profile/ProfileAchievement.tsx
  srcs/front/src/components/profile/ProfileContent.tsx
  srcs/front/src/components/profile/ProfileHistory.tsx
  srcs/front/src/components/profile/ProfileModal.tsx
  srcs/front/src/components/profile/UserInterface.ts
  srcs/front/src/components/styles/ProfileContent.css
  srcs/front/src/routes/pages/ProfilePage.tsx
Labels: enhancement, style

#89 :art: FT-135 [style] 프로필페이지 전반 구조 수정
  srcs/front/src/components/profile/ProfileCard.tsx
  srcs/front/src/components/profile/ProfileContent.tsx
  srcs/front/src/routes/pages/ProfilePage.tsx
Labels: style

#94 Feature/back/game
  srcs/back/src/enums/games.enum.ts
  srcs/back/src/middleware/multer.middleware.ts
  srcs/back/src/modules/chat/chat.gateway.ts
  srcs/back/src/modules/chat/chat.service.ts
  srcs/back/src/modules/chat/class/chat-user.class.ts
  srcs/back/src/modules/direct-message/direct-message.service.ts
  srcs/back/src/modules/games/class/game-ball.class.ts
  srcs/back/src/modules/games/class/game-paddle.class.ts
  srcs/back/src/modules/games/class/game-room.class.ts
  srcs/back/src/modules/games/class/user.class.ts
  srcs/back/src/modules/games/games.gateway.ts
  srcs/back/src/modules/message/dto/create-message.dto.ts
  srcs/back/src/modules/message/entities/message.entity.ts
  srcs/back/src/modules/message/message.service.ts
  srcs/back/src/modules/users/entities/users.entity.ts
  srcs/back/src/modules/users/users.controller.ts
  srcs/back/src/modules/users/users.repository.ts
  srcs/back/src/modules/users/users.service.ts
Labels: enhancement

#95 Feature/front/chatnew
  srcs/front/src/components/chat/Chat.tsx
  srcs/front/src/components/chat/openchat/OpenChatMessage.tsx
  srcs/front/src/components/chat/openchat/OpenChatNoti.tsx
  srcs/front/src/components/chat/openchat/OpenChatRoom.tsx
  srcs/front/src/components/chat/openchat/OpenChatUser.tsx
  srcs/front/src/components/chat/openchat/ProtectedPassword.tsx
  srcs/front/src/components/game/Game.tsx
  srcs/front/src/components/login/Tfa.tsx
  srcs/front/src/index.tsx
Labels: enhancement

#99 Feature/front/profile
  srcs/front/src/components/profile/ProfileContent.tsx
  srcs/front/src/components/profile/ProfileHistory.tsx
  srcs/front/src/components/profile/ProfileMatchHistory.tsx
  srcs/front/src/components/profile/ProfileModal.tsx
  srcs/front/src/components/styles/Modal.css
  srcs/front/src/components/styles/ProfileContent.css
  srcs/front/src/components/styles/button.tsx
  srcs/front/src/components/styles/matchHistory.css
  srcs/front/src/modules/Interfaces/gameMatchInterface.ts
  srcs/front/src/modules/api.ts
Labels: enhancement, style

#100 :art: FT-152 [style] 사용자 전적창 스타일 수정
  srcs/front/src/components/styles/matchHistory.css
Labels: style

#101 :art: FT-153 [style] 에러페이지 수정
  srcs/front/public/img/errorImg.jpg
  srcs/front/src/routes/pages/ErrorPage.tsx
Labels: style
